/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.guacamole.auth.duo;

import org.apache.guacamole.form.Field;

public class DuoPromptField extends Field {

    /**
     * Your API hostname (i.e. api-XXXXXXXX.duosecurity.com).
     */
    private String host;

    /**
     * The signed request generated by sign_request().
     */
    private String sigRequest;

    private static final String DUO_PROMPT_FIELD_TYPE_NAME = "DUO-PROMPT";

    public DuoPromptField(String name, String host, String sigRequest) {
        super(name, DUO_PROMPT_FIELD_TYPE_NAME);
        this.host = host;
        this.sigRequest = sigRequest;
    }

    public String getHost() {
        return host;
    }

    public String getSigRequest() {
        return sigRequest;
    }

}
